version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    allow:
      - dependency-name: "@xmtp/node-sdk"
      - dependency-name: "@xmtp/content-type-remote-attachment"
    groups:
      xmtp:
        patterns:
          - "@xmtp/*"
    open-pull-requests-limit: 5
    labels:
      - dependencies
    commit-message:
      prefix: "chore(deps)"
